### ISSUE TITLE
关于框图

### ISSUE THREAD

**Issue by icey-zhang** [Ding-Kexin/GLT-Net#1]
您好，看了您的论文，论文框图的可视化方式太好了，非常清楚，方便分享一下图片的可编辑源文件吗？

**Comment by Ding-Kexin** [comment]
十分感谢您的肯定，我刚刚上传了源文件，你可以在这里找到：
https://github.com/Ding-Kexin/GLT-Net/blob/main/figure/flow%20chart%20for%20GLT-Net.vsdx

**Comment by icey-zhang** [comment]
您好，请问可以留一个邮箱吗？

**Comment by Ding-Kexin** [comment]
Kexin Ding: dingkexin@hnu.edu.cn
