### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by zugofn** [Ding-Kexin/GLT-Net#3]
作者您好，您的工作很有启发。
我在看代码的过程中发现train_test_gt_1.mat等文件数据仓库里没有提供，请问可否提供一份这些mat文件，或是构建该文件数据的python脚本？
感谢！！

**Comment by Ding-Kexin** [comment]
感谢关注。train_test_gt_1.mat文件是包含训练样本和测试样本的，均为H*W数据，训练样本和测试样本互斥。在我的实验中训练样本是随机选取的，每类选取固定数量用于训练。

**Comment by zugofn** [comment]
收到，多谢😊
